name: NPM Dependency Downloader

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js版本'
        required: true
        default: '18.x'
      npm_version:
        description: 'npm版本'
        required: true
        default: '9.x'
      package_names:
        description: '要下载的插件名，多个插件使用逗号分隔（例如：react,express,lodash）'
        required: true
      package_versions:
        description: '插件版本（留空则使用最新版本），可以为每个插件指定版本，使用逗号分隔，与插件名顺序对应（例如：18.2.0,4.18.2,4.17.21）'
        required: false

jobs:
  download-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      
      - name: 设置Node.js环境
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node_version }}
          # 禁用自动缓存，因为我们在子目录中工作
          cache: 'false'
      
      - name: 安装指定版本的npm
        run: npm install -g npm@${{ github.event.inputs.npm_version }}
      
      - name: 创建临时目录
        run: mkdir -p ./npm-packages && mkdir -p ./package-tarballs
      
      - name: 初始化空项目
        working-directory: ./npm-packages
        run: |
          npm init -y
          npm config set fetch-repo-manifest true
      
      - name: 安装主插件并保存依赖树
        working-directory: ./npm-packages
        run: |
          # 将输入的包名和版本分割成数组
          IFS=',' read -ra PACKAGES <<< "${{ github.event.inputs.package_names }}"
          IFS=',' read -ra VERSIONS <<< "${{ github.event.inputs.package_versions }}"
          
          # 构建安装命令
          INSTALL_CMD="npm install"
          for i in "${!PACKAGES[@]}"; do
            package="${PACKAGES[$i]}"
            # 检查是否有对应的版本指定
            if [ $i -lt ${#VERSIONS[@]} ] && [ -n "${VERSIONS[$i]}" ]; then
              INSTALL_CMD+=" ${package}@${VERSIONS[$i]}"
            else
              INSTALL_CMD+=" ${package}"
            fi
          done
          
          # 添加安装选项并执行
          $INSTALL_CMD --package-lock-only --no-save
          
          # 验证package-lock.json是否存在
          if [ ! -f "package-lock.json" ]; then
            echo "错误: package-lock.json未生成!"
            exit 1
          fi
          
          cat package-lock.json
      
      - name: 下载所有依赖的原始包
        working-directory: ./npm-packages
        run: |
          # 检查license-checker是否安装
          if ! command -v license-checker &> /dev/null
          then
            echo "安装license-checker工具..."
            npm install -g license-checker
          fi
          
          # 下载所有依赖包
          npm pack $(npx -y license-checker --json --onlyDependencies --production | jq -r 'to_entries[] | "\(.key)@\(.value.version)"') --pack-destination ../package-tarballs
          
          # 验证是否下载了包
          if [ -z "$(ls -A ../package-tarballs)" ]; then
            echo "错误: 没有下载任何包!"
            exit 1
          fi
      
      - name: 创建打包文件
        run: |
          tar -czvf npm-packages.tar.gz ./package-tarballs
          echo "ARCHIVE_FILE=npm-packages.tar.gz" >> $GITHUB_ENV
      
      - name: 上传打包文件作为工件
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages
          path: ${{ env.ARCHIVE_FILE }}
          retention-days: 7    
