name: Python Package Download

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version (e.g., 3.8, 3.9)'
        required: true
        default: '3.9'
      package_name:
        description: 'Python package name (e.g., requests)'
        required: true
      package_version:
        description: 'Python package version (e.g., 2.26.0)'
        required: true
      platform:
        description: 'Platform (e.g., linux_x86_64, win_amd64)'
        required: true
        default: 'linux_x86_64'

jobs:
  download-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install pip and wheel
        run: |
          python -m pip install --upgrade pip wheel

      - name: Download packages
        run: |
          pip download ${{ github.event.inputs.package_name }}==${{ github.event.inputs.package_version }} --platform ${{ github.event.inputs.platform }} --only-binary=:all: --dest packages

      - name: Package the downloaded files
        run: |
          zip -r packages.zip packages

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-packages
          path: packages.zip    
